// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTz5piQUYpb4Q6gH6UNBDU6J_6LjVDfH0',
    appId: '1:180466949274:web:3a748dc729b8cff62fd323',
    messagingSenderId: '180466949274',
    projectId: 'food-delivery-287c7',
    authDomain: 'food-delivery-287c7.firebaseapp.com',
    storageBucket: 'food-delivery-287c7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXuU2D9y7uKFIPJ4psLbaVHNcEKZg8Vi8',
    appId: '1:180466949274:android:22b6d1046fd4d45e2fd323',
    messagingSenderId: '180466949274',
    projectId: 'food-delivery-287c7',
    storageBucket: 'food-delivery-287c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo8l5ZL2FZDOl0hppOCjxhY4rFnTN5ZVI',
    appId: '1:180466949274:ios:3eeff1943e9ddcbd2fd323',
    messagingSenderId: '180466949274',
    projectId: 'food-delivery-287c7',
    storageBucket: 'food-delivery-287c7.appspot.com',
    iosClientId: '180466949274-7gogabnfccghkiaimqi82jcsm7bpjs49.apps.googleusercontent.com',
    iosBundleId: 'com.example.fooddelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo8l5ZL2FZDOl0hppOCjxhY4rFnTN5ZVI',
    appId: '1:180466949274:ios:3eeff1943e9ddcbd2fd323',
    messagingSenderId: '180466949274',
    projectId: 'food-delivery-287c7',
    storageBucket: 'food-delivery-287c7.appspot.com',
    iosClientId: '180466949274-7gogabnfccghkiaimqi82jcsm7bpjs49.apps.googleusercontent.com',
    iosBundleId: 'com.example.fooddelivery',
  );
}
